# site base url
baseURL = "https://mochimochiki.github.io/hugo-theme-vivliocli"

# theme directory
themesdir = "../.."

# site title
title = "Hugo theme for Vivliosytle-cli."

theme = "hugo-theme-vivliocli"
languageCode = "en"
defaultContentLanguage = "en"
enableInlineShortcodes = true
disablePathToLower= true
enableGitInfo = false
defaultContentLanguageInSubdir= true
hasCJKLanguage = true
uglyurls = true
relativeURLs = true
canonifyURLs = true

[params]
    # content root directory.
    contentRootDir = "content"

    # theme css. you can add or replace to original css.
    theme_css = [
      "/css/style-main.css",
      "/css/style-browser.css"
      ]

    # book style css. This is loaded for "book: true" pdf. you can add or replace to original css.
    book_css = [ "/css/style-book.css" ]

    # cover page css. you can add or replace to original css.
    cover_css = [ "/css/style-first.css" ]

    # if true, render with pdf mode (suppress menu, etc...)
    isPDF = false

    # The tags defined here can be used in frontmatter and ShowIf/HideIf shortcode.
    showIfs = ["test", "test2", "test3"]

    # output section number level. 3 -> 1.1.1
    sectionNumberLevel = 3

    # If true, enable copy clipboard button on codeblocks.
    copyClipboard = true

    # github edit URL. specify your content directory.
    # editURL = "https://github.com/your/repository/edit/main/content"

    # section delimiter. "-" -> 1-1-2
    # sectionDelimiter = "-"

    # section top format. %s (section number) is needed.
    sectionTopFormat = "Chapter %s"

    # table caption.
    tableCaption = "Table "

    # if true, page counter is started after table of content.
    pageCountAfterToc = true

    # if true, role: "doc-chapter" is rendered as inpage chapter.
    inPageChapterPDF = true

    # if true, output debug log
    debug = false

[languages]
  [languages.ja]
    languageCode = "ja-jp"
    htmlLang = "ja"
    languageName = "Japanese"
    contentDir = "content/ja"
    weight = 1
    dateFormat = "2006年01月02日"
    sectionTopFormat = "第%s章"
    tableCaption = "表 "

    # language css. you can load additional css for this language.
    # lang_css = ["/css/ja.css"]

  [languages.en]
    languageCode = "en"
    htmlLang = "en"
    languageName = "English"
    contentDir = "content/en"
    weight = 2
    dateFormat = "Jan. 2, 2006"
    sectionTopFormat = "Chapter %s"
    tableCaption = "Table "

    # language css. you can load additional css for this language.
    # lang_css = ["/css/en.css"]

# goldmark settings
[markup.goldmark.renderer]
  hardWraps = true
  unsafe = true

# media types / output formats
[mediaTypes]
  [mediaTypes."text/vivlio_config"]
    suffixes = ["vivlio.config.js"]
  [mediaTypes."text/vivlio_cover"]
    suffixes = ["vivlio.cover.html"]
  [mediaTypes."text/vivlio_colophon"]
    suffixes = ["vivlio.colophon.html"]
[outputFormats]
  [outputFormats.VIVLIO_CONFIG]
    isPlainText = true
    mediaType = "text/vivlio_config"
  [outputFormats.VIVLIO_COVER]
    isPlainText = true
    mediaType = "text/vivlio_cover"
  [outputFormats.VIVLIO_COLOPHON]
    isPlainText = true
    mediaType = "text/vivlio_colophon"
