name: Build PDF CI

on:
  push:
    branches: [ add-docker ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build PDF
      run: |
        docker build . --file Dockerfile --tag hugo-theme-vivliocli:$(date +%s)
        docker run -v .:/hugo-theme-vivliocli --init --rm --cap-add=SYS_ADMIN hugo-theme-vivliocli:$(date +%s) pdf

    - uses: actions/upload-artifact@v2
      with:
        name: pdf
        path: exampleSite/public_pdf/jp/Guide.pdf